# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Yellow_circles(object):
    def setupUi(self, Yellow_circles):
        Yellow_circles.setObjectName("Yellow_circles")
        Yellow_circles.resize(648, 357)
        self.centralwidget = QtWidgets.QWidget(Yellow_circles)
        self.centralwidget.setObjectName("centralwidget")
        self.push = QtWidgets.QPushButton(self.centralwidget)
        self.push.setGeometry(QtCore.QRect(260, 290, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.push.setFont(font)
        self.push.setObjectName("push")
        Yellow_circles.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Yellow_circles)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 648, 21))
        self.menubar.setObjectName("menubar")
        Yellow_circles.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Yellow_circles)
        self.statusbar.setObjectName("statusbar")
        Yellow_circles.setStatusBar(self.statusbar)

        self.retranslateUi(Yellow_circles)
        QtCore.QMetaObject.connectSlotsByName(Yellow_circles)

    def retranslateUi(self, Yellow_circles):
        _translate = QtCore.QCoreApplication.translate
        Yellow_circles.setWindowTitle(_translate("Yellow_circles", "MainWindow"))
        self.push.setText(_translate("Yellow_circles", "Нарисовать"))
